# Generated by Django 5.1 on 2024-09-02 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackNumGenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel_order',
            old_name='created_at',
            new_name='order_created_at',
        ),
        migrations.AddField(
            model_name='parcel_order',
            name='trackingNo_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
